---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - name: golang-image-new
        image: dikshasahu/golang-image-new
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
